# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Text(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Text()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsText(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Text
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Text
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(1)
def TextStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddText(builder, text): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)
def TextAddText(builder, text):
    """This method is deprecated. Please switch to AddText."""
    return AddText(builder, text)
def End(builder): return builder.EndObject()
def TextEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)