# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EditCameraAimCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EditCameraAimCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEditCameraAimCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EditCameraAimCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EditCameraAimCommand
    def Edit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(1)
def EditCameraAimCommandStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddEdit(builder, edit): builder.PrependBoolSlot(0, edit, 0)
def EditCameraAimCommandAddEdit(builder, edit):
    """This method is deprecated. Please switch to AddEdit."""
    return AddEdit(builder, edit)
def End(builder): return builder.EndObject()
def EditCameraAimCommandEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)