# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OpenSceneCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OpenSceneCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOpenSceneCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OpenSceneCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OpenSceneCommand
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OpenSceneCommand
    def Options(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from fbs.Viewer.fbs.Option import Option
            obj = Option()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OpenSceneCommand
    def OptionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OpenSceneCommand
    def OptionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Start(builder): builder.StartObject(2)
def OpenSceneCommandStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddPath(builder, path): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)
def OpenSceneCommandAddPath(builder, path):
    """This method is deprecated. Please switch to AddPath."""
    return AddPath(builder, path)
def AddOptions(builder, options): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(options), 0)
def OpenSceneCommandAddOptions(builder, options):
    """This method is deprecated. Please switch to AddOptions."""
    return AddOptions(builder, options)
def StartOptionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OpenSceneCommandStartOptionsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartOptionsVector(builder, numElems)
def End(builder): return builder.EndObject()
def OpenSceneCommandEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)