# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetClippingCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetClippingCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetClippingCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetClippingCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetClippingCommand
    def Method(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SetClippingCommand
    def Plane(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(2)
def SetClippingCommandStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddMethod(builder, method): builder.PrependInt32Slot(0, method, 0)
def SetClippingCommandAddMethod(builder, method):
    """This method is deprecated. Please switch to AddMethod."""
    return AddMethod(builder, method)
def AddPlane(builder, plane): builder.PrependInt32Slot(1, plane, 0)
def SetClippingCommandAddPlane(builder, plane):
    """This method is deprecated. Please switch to AddPlane."""
    return AddPlane(builder, plane)
def End(builder): return builder.EndObject()
def SetClippingCommandEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)